synestetic_pitch:
  note_sequence: [C4, G4, F3, E4, A3, F4, H3, D4, G3, A4, C#4, E3, F#4, H4, D#4, D3, G#4, C5]
  start_with_notes: 4
  guess_questions: 5
  session_length_minutes: 20
  maximum_note_score: 100
  minumum_instant_sessions: 3
  default_instant_sessions: 7
  maximum_instant_sessions: 15
  morning_session_scores: 10
  morning_session_penalty: 5
  morning_session_settings:
    scores: 10
    penalty: 5
    notes: 6
  instant_session_settings:
    scores: 20
    penalty: 5
    max_inactivity_minutes: 15
    notes: 2
  practice_session_settings:
    scores: 3
    penalty: 1
    reset_after_minutes: 10
    scored_notes: 1